<?php

namespace Modules\Production\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProTybesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'pname' => 'سند قبض',
                'ptext' => null,
                'ptybe' => 1,
                'info' => null,
                'crtime' => '2024-03-14 02:01:35',
                'mdtime' => '2024-03-14 02:01:35',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 2,
                'pname' => 'سند دفع',
                'ptext' => null,
                'ptybe' => 2,
                'info' => null,
                'crtime' => '2024-03-14 02:01:35',
                'mdtime' => '2024-03-14 02:02:22',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 3,
                'pname' => 'فاتورة مبيعات',
                'ptext' => null,
                'ptybe' => 3,
                'info' => null,
                'crtime' => '2024-03-14 02:01:58',
                'mdtime' => '2024-03-14 02:02:26',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 4,
                'pname' => 'فاتورة مشتريات',
                'ptext' => null,
                'ptybe' => 4,
                'info' => null,
                'crtime' => '2024-03-14 02:01:58',
                'mdtime' => '2024-03-14 02:02:28',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 5,
                'pname' => 'استحقاق قسط',
                'ptext' => null,
                'ptybe' => 5,
                'info' => null,
                'crtime' => '2024-03-17 03:53:16',
                'mdtime' => '2024-03-17 03:53:27',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 6,
                'pname' => 'خصم مكتسب',
                'ptext' => null,
                'ptybe' => 6,
                'info' => null,
                'crtime' => '2024-03-17 03:53:16',
                'mdtime' => '2024-03-17 03:53:27',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 7,
                'pname' => 'خصم مسموح به',
                'ptext' => null,
                'ptybe' => 7,
                'info' => null,
                'crtime' => '2024-03-17 03:53:16',
                'mdtime' => '2024-03-17 03:53:27',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 8,
                'pname' => 'قيد يومية',
                'ptext' => null,
                'ptybe' => 8,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-05-14 11:06:54',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 9,
                'pname' => 'فاتورة كاشير',
                'ptext' => null,
                'ptybe' => 9,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-07-19 17:25:29',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 10,
                'pname' => 'فاتورة مردود مبيعات',
                'ptext' => null,
                'ptybe' => 10,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-21 15:25:06',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 11,
                'pname' => 'فاتورة مردود مشتريات',
                'ptext' => null,
                'ptybe' => 11,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-21 15:25:10',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 12,
                'pname' => 'أمر شراء',
                'ptext' => null,
                'ptybe' => 12,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-21 15:25:12',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 13,
                'pname' => 'أمر بيع',
                'ptext' => null,
                'ptybe' => 13,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-21 15:25:16',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 14,
                'pname' => 'رصيد افتتاحي مخازن',
                'ptext' => null,
                'ptybe' => 14,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-23 11:40:49',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
            [
                'id' => 15,
                'pname' => 'رصيد افتتاحي حسابات',
                'ptext' => null,
                'ptybe' => 15,
                'info' => null,
                'crtime' => '2024-05-14 11:06:41',
                'mdtime' => '2024-11-23 11:40:52',
                'isdeleted' => 0,
                'tenant' => 0,
                'branch' => 0,
            ],
        ];

        foreach ($data as $row) {
            DB::table('pro_tybes')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }
}
